css:
js:
  bundles:
    index:     
      - head.load.min
      - jquery.easing
      - font     
      - showdown  
      - jquery.scrollTo-1.4.2 
      - jquery.nivo.slider
      - index  
    post:        
      - head.load.min
      - jquery.easing
      - font         
      - showdown   
      - jquery.scrollTo-1.4.2 
      - jquery.nivo.slider
      - index          
      - jquery.labelify   
      - jquery.form
      - jquery.autocomplete
      - helpers
      - post